workstations:
  hosts:
    geryon:
      ansible_host: 192.168.1.108
      ansible_user: cbugra
      # run options -k and -K to ask password instead
      #ansible_ssh_private_key_file: /home/cbugra/.ssh/geryon_ssh

